// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGoCRJgxXNzdzDidHZv7UIKhNAmCrlamI',
    appId: '1:937263915138:web:1c83b864639029cdf2549b',
    messagingSenderId: '937263915138',
    projectId: 'sustav-za-zavod-za-zdravstvo',
    authDomain: 'sustav-za-zavod-za-zdrav-7c514.firebaseapp.com',
    storageBucket: 'sustav-za-zavod-za-zdravstvo.appspot.com',
    measurementId: 'G-S6R9106326',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIOU1C7aQ3lukk_xyquXByAuZ0p8bRCug',
    appId: '1:937263915138:android:bf293817852d74a8f2549b',
    messagingSenderId: '937263915138',
    projectId: 'sustav-za-zavod-za-zdravstvo',
    storageBucket: 'sustav-za-zavod-za-zdravstvo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMo3YEaOerXw_dVmBZNxuGZ6e-MirgKTc',
    appId: '1:937263915138:ios:7225fbddeb03fcb0f2549b',
    messagingSenderId: '937263915138',
    projectId: 'sustav-za-zavod-za-zdravstvo',
    storageBucket: 'sustav-za-zavod-za-zdravstvo.appspot.com',
    androidClientId: '937263915138-6m05t083i9tde15542iu6tv0rjcds9j7.apps.googleusercontent.com',
    iosClientId: '937263915138-in29gn0uschjefks9idkec58dkgacoe1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sustavZaTransfuziologiju',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMo3YEaOerXw_dVmBZNxuGZ6e-MirgKTc',
    appId: '1:937263915138:ios:4206a2b162b3a511f2549b',
    messagingSenderId: '937263915138',
    projectId: 'sustav-za-zavod-za-zdravstvo',
    storageBucket: 'sustav-za-zavod-za-zdravstvo.appspot.com',
    androidClientId: '937263915138-6m05t083i9tde15542iu6tv0rjcds9j7.apps.googleusercontent.com',
    iosClientId: '937263915138-9hvh7k1jqkd6ke21na4ir26pj8ch5sdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sustavZaTransfuziologiju.RunnerTests',
  );
}
