import 'package:flutter/material.dart';

const appBarTextStyle = TextStyle(fontWeight: FontWeight.bold, color: Colors.white);
const filterBorderWidth = 2.0;
final borderRadius = BorderRadius.circular(20.0);
const listItemBorderWidth = 2.0;
const listItemElevation = 2.0;
const listItemMargin = EdgeInsets.symmetric(vertical: 8.0, horizontal: 16.0);
final headerBackgroundColor = Colors.red[900];
const cardColor = Colors.white;
const rejectReasonColor = Colors.red;
const mainAxisAlignment = MainAxisAlignment.center;
const acceptedBorderColor = Colors.green;
const rejectedBorderColor = Colors.red;
const spinKitColor = Colors.red;
const crossAxisAlignment = CrossAxisAlignment.start;
const cardTextStyle = FontWeight.bold;
const svgHeight = 50.0;
const svgWidth = 50.0;
const dropdownTextStyle = TextStyle(color: Colors.black);
const dropDownColor = Colors.white;
const dropdownIcon = Icon(Icons.arrow_drop_down);
const dropDownElevation = 0;
const rejectionReasonColor = TextStyle(color: Colors.red);
const dropDownPadding = EdgeInsets.fromLTRB(12.0, 4.0, 4.0, 4.0);
const sizedBoxHeight = 20.0;
const sizedBoxWidth = 20.0;
const dropDownMargin = EdgeInsets.symmetric(vertical: 30.0, horizontal: 20.0);